# Generated by Django 5.1.4 on 2025-01-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_subject_votingpanel_votingitem_vote_voting_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VotingPanel',
            new_name='Poll',
        ),
    ]
